### PR TITLE
vars.tf => variables.tf

### PR DESCRIPTION
**Pull request by yorinasub17**
This is slightly more controversial, but updates the usage of vars.tf to variables.tf given that this is now what the official terraform docs recommends (and how we have been slowly migrating towards it).

The one issue is I am not sure if the slides still reference vars.tf. I am going through the deck now to cross reference.

### CODE REVIEW

**Comment by josh-padnick** [comment]
I don't have a strong opinion on this. I prefer `vars.tf` because it's shorter and conveys the same information, but HashiCorp decided that `variables.tf` is their official spec and in fact their module registry requires that name as well.

For that reason, it probably does make sense to switch to `variables.tf`.

**Comment by yorinasub17** [comment]
> I don't have a strong opinion on this. I prefer `vars.tf` because it's shorter and conveys the same information, but HashiCorp decided that `variables.tf` is their official spec and in fact their module registry requires that name as well.
> For that reason, it probably does make sense to switch to `variables.tf`.

Funny enough, I share the exact same sentiment, down to the conclusion of why we should do this.

**Comment by brikis98** [comment]
+1 here as well on everything Josh said

**Comment by yorinasub17** [comment]
Ok merging this in

**Pull request merged**
